import type { Metadata } from "next";
import "./globals.css";

import Image from "next/image";
import backgroundImage from "../../public/backgroundImage.png";

import { Roboto_Serif } from "next/font/google";
import Header from "@/components/Header";

const Roboto = Roboto_Serif({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: {
    template: "%s - Just Movie",
    default: "Just Movie - Sharing The Most Popular Movies",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Roboto.className} antialiased relative`}>
        <Image
          className="object-cover -z-50"
          placeholder="blur"
          quality={10}
          fill
          src={backgroundImage}
          alt="Just Movie - Background Image"
        />
        <Header />

        <main className="container mx-auto px-10">{children}</main>
      </body>
    </html>
  );
}
